Workaround missing noexcept for std::string move assignment (#87)
Due to GCC/libstdc++ bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58265
the string move assignment may be missing noexcept, resulting in build
errors even with relative recent GCC versions:

```
nanobench.h:2898:9: error: function 'ankerl::nanobench::Config& ankerl::nanobench::Config::operator=(ankerl::nanobench::Config&&)' defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ''
 Config& Config::operator=(Config&&) noexcept = default;
         ^~~~~~
```